services:
  - type: web
    name: unilibrary-pro-bex040598
    repo: https://github.com/bex040598/unilibrary-pro
    branch: main
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
