services:
  - type: web
    name: unilibrary-pro-2
    branch: main
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npx next start --hostname 0.0.0.0 --port $PORT
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
